# Generated by Django 4.1.5 on 2023-01-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField(max_length=100)),
                ('house', models.TextField(max_length=10)),
                ('apart', models.TextField(max_length=10)),
                ('zip', models.TextField(max_length=6)),
                ('city', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('lname', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.address')),
            ],
        ),
    ]
